package com.abc.movies.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Movies")
public class Movie {      
	  private String id;
      private String title; 
      private String image;
      private String category;
      private int rate;
      
      public Movie() {
    	  
      }
      
      @Override
  	public int hashCode() {
  		final int prime = 31;
  		int result = 1;
  		result = prime * result + ((title == null) ? 0 : title.hashCode());
  		return result;
  	}
      
  	@Override
  	public boolean equals(Object obj) {
  		if (this == obj)
  			return true;
  		if (obj == null)
  			return false;
  		if (getClass() != obj.getClass())
  			return false;
  		Movie other = (Movie) obj;
  		if (title == null) {
  			if (other.title != null)
  				return false;
  		} else if (!title.equals(other.title))
  			return false;
  		return true;
  	}
  	
  	@DynamoDBAttribute(attributeName = "Id")
  	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBHashKey(attributeName = "Title")
	public String getTitle() {
		return title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	@DynamoDBAttribute(attributeName = "Image")
	public String getImage() {
		return image;
	}
	
	public void setImage(String image) {
		this.image = image;
	}
	
	@DynamoDBAttribute(attributeName = "Category")
	public String getCategory() {
		return category;
	}
	
	public void setCategory(String category) {
		this.category = category;
	}

	@Override
	public String toString() {
		return "Movie [id=" + id + ", title=" + title + ", image=" + image + ", category=" + category + "]";
	}

	 @DynamoDBRangeKey(attributeName = "Rate")
	public int getRate() {
		return rate;
	}

	public void setRate(int rate) {
		this.rate = rate;
	}
	
}
